[toolchain]
channel = "nightly-2024-12-01"
components = ["rustfmt", "clippy", "audit"]
targets = ["x86_64-unknown-linux-gnu", "x86_64-pc-windows-msvc", "x86_64-apple-darwin", "wasm32-unknown-unknown"]